name: Backend

on:
  push:
    branches:
      - feature/**
    paths:
      - backend/**

jobs:
  Backend:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install java 11 (Temurin)
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Set up Maven 3.8.4
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.4
      - name: Test the backend
        working-directory: ./backend
        run: mvn clean test
      - name: Generate the backend coverage badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: backend/target/site/jacoco/jacoco.csv
          coverage-badge-filename: backend-jacoco.svg
      - name: Commit the backend badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated backend JaCoCo coverage badge"
            git push
          fi
      - name: Build the backend
        working-directory: ./backend
        run: mvn clean install
      - name: Archive Backend jar
        uses: actions/upload-artifact@v2
        with:
          name: backend-jar
          path: |
            backend/target/simpleTCFS*.jar
      - name: Archive jacoco coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-coverage-report
          path: |
            backend/target/site/jacoco
